// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5i9neNKO4m6e4TjL35q4_H7IMaDOTHDw',
    appId: '1:1095425139783:web:9b3fa980bf24cc15547d62',
    messagingSenderId: '1095425139783',
    projectId: 'eduhub-app-96325',
    authDomain: 'eduhub-app-96325.firebaseapp.com',
    storageBucket: 'eduhub-app-96325.firebasestorage.app',
    measurementId: 'G-EQZYSX2SFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ0DiX0fvsSpFV374TB2ktYCW2ErvPdf4',
    appId: '1:1095425139783:android:7722c4826ba058cb547d62',
    messagingSenderId: '1095425139783',
    projectId: 'eduhub-app-96325',
    storageBucket: 'eduhub-app-96325.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7dGs6Ya9WacNuMSZ9gYAiYg3YvlQPqrE',
    appId: '1:1095425139783:ios:b5550d0634f243b0547d62',
    messagingSenderId: '1095425139783',
    projectId: 'eduhub-app-96325',
    storageBucket: 'eduhub-app-96325.firebasestorage.app',
    iosBundleId: 'com.example.eduhub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7dGs6Ya9WacNuMSZ9gYAiYg3YvlQPqrE',
    appId: '1:1095425139783:ios:b5550d0634f243b0547d62',
    messagingSenderId: '1095425139783',
    projectId: 'eduhub-app-96325',
    storageBucket: 'eduhub-app-96325.firebasestorage.app',
    iosBundleId: 'com.example.eduhub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5i9neNKO4m6e4TjL35q4_H7IMaDOTHDw',
    appId: '1:1095425139783:web:45653682536859b7547d62',
    messagingSenderId: '1095425139783',
    projectId: 'eduhub-app-96325',
    authDomain: 'eduhub-app-96325.firebaseapp.com',
    storageBucket: 'eduhub-app-96325.firebasestorage.app',
    measurementId: 'G-BB6PLYXY1V',
  );

}